# Shared Dev Stack (ARM64-native) — August 2025
#
# Apple Silicon friendly development services only (no amd64 emulation).
# Includes: Postgres+pgvector, Redis, ArangoDB, Redpanda (Kafka-compatible).

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: zen
      POSTGRES_INITDB_ARGS: "-c shared_preload_libraries=vector"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  arangodb:
    image: arangodb:3.12
    environment:
      ARANGO_ROOT_PASSWORD: root
      ARANGO_STORAGE_ENGINE: rocksdb
    ports:
      - "8529:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8529/_api/version"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.1
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --check=false
      - --kafka-addr
      - 0.0.0.0:9092
      - --advertise-kafka-addr
      - redpanda:9092
    ports:
      - "9092:9092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  # Ollama (ARM64-native) for local embeddings
  ollama:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  # Meilisearch (lightweight faceted search)
  meilisearch:
    image: getmeili/meilisearch:v1.9
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=dev-master-key
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  pgdata:
  arangodb_data:
  arangodb_apps:
  redpanda_data:
  ollama_data:
  meili_data:
