apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: zen_mcp
    user: zen_user
    secureJsonData:
      password: zen_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: true

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    jsonData:
      client: standalone
    editable: true