name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Validate OpenAPI
        run: |
          python scripts/validate_openapi.py
      - name: Run tests (unit + http, parallel)
        env:
          ZEN_STORAGE_MODE: memory
        run: |
          pytest -n auto --dist=loadscope -q \
            tests/test_router_and_messaging.py \
            tests/test_http_endpoints_router_messaging.py \
            tests/test_tools_toggle.py

  postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: zen_mcp
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" \
          --health-interval 5s \
          --health-timeout 5s \
          --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Init database schema
        env:
          PG_DSN: postgresql://postgres:postgres@localhost:5432/zen_mcp
        run: |
          python scripts/db_init.py
      - name: Run messaging + project tests on Postgres
        env:
          ZEN_STORAGE: postgres
          PG_DSN: postgresql://postgres:postgres@localhost:5432/zen_mcp
        run: |
          pytest -q tests/test_http_endpoints_router_messaging.py::test_channel_and_dm_roundtrip -q || true
          pytest -q tests/test_router_and_messaging.py -q || true
